{
  "hash": "d6adf9cb4de7346024c95e317037caae",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bloque I: Análisis de Componentes Principales\"\nformat: html\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(factoextra)\nlibrary(corrplot)\nlibrary(psych)\nset.seed(230205)\n\namazon_df       <- read_rds(\"amazon_df.rds\")\namazon_productos <- read_rds(\"amazon_productos.rds\")\n```\n:::\n\n\n## Análisis Exploratorio y Adecuación Muestral\n\nEl Análisis de Componentes Principales (PCA) transforma un conjunto de variables correlacionadas en componentes ortogonales ordenadas por varianza explicada. Antes de ejecutarlo es necesario verificar que existe suficiente estructura correlacional en los datos.\n\n### Matriz de correlaciones\n\n\n::: {.cell}\n\n```{.r .cell-code}\namazon_numeric <- amazon_productos |> select(-ProductId)\n\ncor(amazon_numeric) |> \n  corrplot(method = \"number\",\n           type = \"upper\",\n           col = colorRampPalette(c(\"#BB4444\", \"#EE9988\", \"#FFFFFF\", \"#77AADD\", \"#4477AA\"))(200))\n```\n\n::: {.cell-output-display}\n![](pca_files/figure-html/pca-correlacion-1.png){width=672}\n:::\n:::\n\n\nLa matriz revela una correlación negativa fuerte entre `score_medio` y `score_entropy` (−0.71): los productos con puntuaciones altas tienden a generar distribuciones de votos menos dispersas. Por su parte, `longitud_media` y las métricas de polaridad muestran covarianza positiva, sugiriendo que las reseñas más largas suelen ser más polarizadas en tono.\n\n### Tests de Bartlett y KMO\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncortest.bartlett(cor(amazon_numeric), n = nrow(amazon_numeric))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$chisq\n[1] 7440.4\n\n$p.value\n[1] 0\n\n$df\n[1] 36\n```\n\n\n:::\n\n```{.r .cell-code}\nKMO(amazon_numeric)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKaiser-Meyer-Olkin factor adequacy\nCall: KMO(r = amazon_numeric)\nOverall MSA =  0.71\nMSA for each item = \n    total_resenas    longitud_media          lifespan helpfulness_medio \n             0.44              0.64              0.45              0.81 \n  polaridad_media      polaridad_sd       score_medio          score_sd \n             0.71              0.63              0.73              0.76 \n    score_entropy \n             0.76 \n```\n\n\n:::\n:::\n\n\nEl **test de esfericidad de Bartlett** contrasta la hipótesis nula de que la matriz de correlaciones es la identidad. Con p-valor ≈ 0, se rechaza con total seguridad, dado que existe correlación significativa entre las variables y el PCA tiene sentido estadístico.\n\nEl **índice KMO** mide en qué medida las correlaciones observadas pueden explicarse por factores comunes, con valores entre 0 y 1. El KMO global de **0.71** normalmente se considera un valor aceptable. Las variables `helpfulness_medio` (0.81), `score_medio` (0.73) y `score_entropy` (0.76) presentan los valores más altos. Las variables `total_resenas` (0.44) y `lifespan` (0.45) quedan por debajo de 0.5, el umbral habitual de aceptabilidad, lo que es esperable dado que miden la escala y la antigüedad del producto y no la opinión del usuario. Por ello se **excluyen del PCA**, aunque se conservan como atributos de nodo en el análisis de redes.\n\n## Tratamiento de Outliers y PCA\n\n### Winsorización por IQR\n\n\n::: {.cell}\n\n```{.r .cell-code}\namazon_productos |>\n  select(-ProductId) |>\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"valor\") |>\n  ggplot(aes(x = variable, y = valor)) +\n  geom_boxplot() +\n  facet_wrap(~variable, scales = \"free\") +\n  labs(title = \"Distribución original de las variables\") +\n  theme(axis.text.x = element_blank())\n```\n\n::: {.cell-output-display}\n![](pca_files/figure-html/pca-outliers-1.png){width=672}\n:::\n\n```{.r .cell-code}\nwinsorize_iqr <- function(x) {\n  q1  <- quantile(x, 0.25, na.rm = TRUE)\n  q3  <- quantile(x, 0.75, na.rm = TRUE)\n  iqr <- q3 - q1\n  pmax(pmin(x, q3 + 1.5 * iqr), q1 - 1.5 * iqr)\n}\n\namazon_numeric <- amazon_numeric |>\n  select(-total_resenas, -lifespan) |> # <1>\n  mutate(across(everything(), winsorize_iqr))\n\namazon_numeric |>\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"valor\") |>\n  ggplot(aes(x = variable, y = valor)) +\n  geom_boxplot() +\n  facet_wrap(~variable, scales = \"free\") +\n  labs(title = \"Distribución tras la winsorización\") +\n  theme(axis.text.x = element_blank())\n```\n\n::: {.cell-output-display}\n![](pca_files/figure-html/pca-outliers-2.png){width=672}\n:::\n:::\n\n1. Variables descartadas por su bajo KMO individual.\n\nLos boxplots originales muestran outliers severos en `total_resenas` y `lifespan`, además de unos cuantos en las métricas de polaridad y de longitud media. Dado que el PCA maximiza la varianza, estos valores distorsionarían las componentes. Las dos primeras ya quedan fuera del PCA por su bajo KMO; a las siete variables restantes se les aplica **winsorización por IQR**: los valores fuera de `[Q1 − 1.5·IQR, Q3 + 1.5·IQR]` se recortan a los límites, manteniendo cierta magnitud de los extremos sin que dominen el análisis.\n\n### Ejecución del PCA y Scree Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_amazon <- prcomp(amazon_numeric, center = TRUE, scale = TRUE) # <1>\n\nfviz_eig(pca_amazon, \n         addlabels = TRUE, \n         ylim = c(0, 80), \n         title = \"Scree Plot: Varianza Explicada por Componente\")\n```\n\n::: {.cell-output-display}\n![](pca_files/figure-html/pca-ejecucion-1.png){width=672}\n:::\n:::\n\n1. La estandarización incluida en los parámetros del pca es imprescindible cuando las variables tienen unidades y escalas diferentes.\n\nEl **Scree Plot** muestra un codo pronunciado tras la tercera componente: PC1 explica el 40.1%, PC2 el 25.7% y PC3 el 13.4%. A partir de PC4 la curva se aplana.\n\n### Selección de componentes: criterio de Kaiser\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautovalores <- pca_amazon$sdev^2\ncomponentes <- data.frame(\n  componente = paste0(\"PC\", seq_along(autovalores)),\n  autovalor  = round(autovalores, 3),\n  varianza_pct = round(autovalores / sum(autovalores) * 100, 1),\n  varianza_acum = round(cumsum(autovalores) / sum(autovalores) * 100, 1)\n)\ncomponentes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  componente autovalor varianza_pct varianza_acum\n1        PC1     2.808         40.1          40.1\n2        PC2     1.802         25.7          65.9\n3        PC3     0.935         13.4          79.2\n4        PC4     0.510          7.3          86.5\n5        PC5     0.486          6.9          93.4\n6        PC6     0.274          3.9          97.4\n7        PC7     0.185          2.6         100.0\n```\n\n\n:::\n:::\n\n\nEl **criterio de Kaiser** establece retener las componentes con autovalor superior a 1, ya que un autovalor de 1 equivale a la varianza de una variable estandarizada. El criterio selecciona las dos primeras (65.9% de varianza acumulada), pero dada la diferencia apreciable entre PC3 y las restantes, se incluyen las **tres primeras componentes** con un 79.2% de varianza retenida — una retención buena con menos de la mitad de las siete variables de entrada.\n\n## Interpretación de las Componentes\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_amazon$rotation[, 1:3] |>\n  as.data.frame() |>\n  rownames_to_column(\"Variable\") |>\n  knitr::kable(digits = 3, caption = \"Cargas de cada variable en las tres primeras componentes\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Cargas de cada variable en las tres primeras componentes\n\n|Variable          |    PC1|    PC2|    PC3|\n|:-----------------|------:|------:|------:|\n|longitud_media    |  0.052|  0.613| -0.080|\n|helpfulness_medio | -0.192| -0.011| -0.977|\n|polaridad_media   | -0.298|  0.481|  0.100|\n|polaridad_sd      |  0.060|  0.621|  0.007|\n|score_medio       | -0.553| -0.018|  0.091|\n|score_sd          |  0.541|  0.048| -0.069|\n|score_entropy     |  0.519|  0.068| -0.128|\n\n\n:::\n\n```{.r .cell-code}\nfviz_pca_var(pca_amazon, \n             col.var = \"contrib\",\n             gradient.cols = c(\"#00AFBB\", \"#E7B800\", \"#FC4E07\"),\n             repel = TRUE, \n             title = \"Variables y sus contribuciones en el Ecosistema Amazon\")\n```\n\n::: {.cell-output-display}\n![](pca_files/figure-html/pca-contribuciones-1.png){width=672}\n:::\n:::\n\n\nLa tabla de cargas permite interpretar qué mide cada componente:\n\n- **PC1** recibe contribuciones altas de `score_medio`, `score_sd`, `score_entropy` y `polaridad_media`. Separa productos de alta satisfacción y consenso (cargas positivas/negativas opuestas entre score y entropy) de productos con opiniones dispares. Podría interpretarse como un eje de **calidad percibida**.\n- **PC2** está dominada por `longitud_media`, `polaridad_sd` y, en menor medida, `polaridad_media`. Distingue productos cuyas reseñas son extensas y de tono variado frente a productos con reseñas breves y homogéneas. Representa el **grado de elaboración de las reseñas**.\n- **PC3** captura, casi por completo en comparación con las otras variables, el **helpfulness de las reseñas**, por lo que prioriza la disposición de las personas de criticar positivamente el producto.\n\n### Verificación de ortogonalidad\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(pca_amazon$x) |>\n  corrplot(method = \"number\", type = \"upper\",\n           title = \"Correlación entre Componentes Principales\")\n```\n\n::: {.cell-output-display}\n![](pca_files/figure-html/pca-ortogonalidad-1.png){width=672}\n:::\n:::\n\n\nLas correlaciones entre scores son 0 (salvo errores de redondeo numérico), confirmando que cada componente captura una dimensión genuinamente distinta.\n\n## Clustering y Biplot\n\nPara poder cruzar los resultados del PCA con el análisis SNA, se aplica un k-means sobre los scores de las tres primeras componentes. Se utiliza el **método del codo** para determinar el número óptimo de clusters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_nbclust(pca_amazon$x[, 1:3], kmeans, method = \"wss\") +\n  labs(title = \"Método del codo para selección de k\")\n```\n\n::: {.cell-output-display}\n![](pca_files/figure-html/pca-codo-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(230205)\nk_optimo <- 3  # <1>\nclusters_pca <- kmeans(pca_amazon$x[, 1:3], centers = k_optimo)\npca_clusters <- data.frame(\n  ProductId = amazon_productos$ProductId,\n  cluster_pca = as.factor(clusters_pca$cluster)\n)\nwrite_rds(pca_clusters, \"pca_clusters.rds\")\n\npca_scores <- data.frame(ProductId = amazon_productos$ProductId, pca_amazon$x[, 1:3]) # <2>\nattr(pca_scores, \"varianza_pct\") <- componentes$varianza_pct[1:3]\nwrite_rds(pca_scores, \"pca_scores.rds\")\n```\n:::\n\n1. El valor de `k` se selecciona a partir del gráfico del codo: el punto donde la reducción de la suma de cuadrados intra-cluster deja de ser sustancial.\n2. Se exportan los scores y la varianza explicada para que las conclusiones reutilicen exactamente este PCA en lugar de recalcularlo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_pca_biplot(pca_amazon,\n                geom.ind  = \"point\",\n                pointsize = 1.2,\n                alpha.ind = 0.3,\n                col.ind   = pca_clusters$cluster_pca,\n                palette   = c(\"#9ecae1\", \"#fdae6b\", \"#a1d99b\", \"#c9a0dc\"),\n                addEllipses    = TRUE,\n                ellipse.level  = 0.95,\n                ellipse.type   = \"confidence\",\n                col.var   = \"black\",\n                repel     = TRUE,\n                legend.title = \"Cluster PCA\",\n                title = \"Biplot de Productos de Amazon\")\n```\n\n::: {.cell-output-display}\n![](pca_files/figure-html/pca-biplot-1.png){width=864}\n:::\n:::\n\n",
    "supporting": [
      "pca_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}